apiVersion: apps/v1
kind: Deployment
metadata:
  name: apistore-deployment
  labels:
    app: api-store
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api-store
    spec:
      containers:
      - name: api-store
        image: sanjanakr/api-store
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: api-store
        
---
apiVersion: v1
kind: Service
metadata:
  name: api-store-svc
  namespace: default
spec:
  selector:
    app: api-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-store-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: api-store-svc
            port:
              number: 80